=== MukeshV711/EP-Practical/Student form/WebContent/task2.dtd
<!ELEMENT students_info (student+)>
<!ELEMENT student (regno,name,avg,dob,mobileno,distinction)>
<!ELEMENT regno (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT avg (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT mobileno (#PCDATA)>
<!ELEMENT distinction (#PCDATA)>

=== MukeshV711/EP-Practical/Student form/WebContent/task2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students_info SYSTEM "task2.dtd">
<students_info>
<student>         
   <regno>1900</regno>
   <name>Mukesh</name>    
   <avg>85</avg>
   <dob>09-05-1993</dob>         
    <mobileno>1234567890</mobileno>         
   <distinction>YES</distinction>
 </student>
 <student>         
   <regno>1900</regno>
   <name>Kushal</name>    
   <avg>92</avg>
   <dob>15-08-1992</dob>       
   <mobileno>1234567890</mobileno>         
   <distinction>YES</distinction>
 </student>
 <student>         
   <regno>1900</regno>
   <name>Nikhil</name>    
   <avg>81</avg>
   <dob>22-10-1991</dob>        
    <mobileno>1900</mobileno>         
   <distinction>YES</distinction>
 </student>
 <student>         
   <regno>1900</regno>
   <name>abhi</name>    
   <avg>98</avg>
   <dob>01-01-1994</dob>  
         
    <mobileno>1234567890</mobileno>          
   <distinction>YES</distinction>
 </student>
 <student>         
   <regno>1900</regno>
   <name>Hruthik</name>    
   <avg>90</avg>
   <dob>30-12-1992</dob>         
   <mobileno>1234567890</mobileno>         
   <distinction>YES</distinction>
 </student>
 
</students_info>

=== MukeshV711/EP-Practical/Jan-4/WebContent/Task2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students_info SYSTEM "Task2.dtd">
<students_info>
<student>         
   <regno>170024</regno>
   <name>Naveen</name>    
   <avg>85</avg>
   <dob>09-05-1993</dob>         
    <mobileno>9849984901</mobileno>         
   <distinction>YES</distinction>
 </student>
 <student>         
   <regno>170025</regno>
   <name>sharooq</name>    
   <avg>92</avg>
   <dob>15-08-1992</dob>       
   <mobileno>9849984901</mobileno>         
   <distinction>YES</distinction>
 </student>
 <student>         
   <regno>170026</regno>
   <name>Sadiq</name>    
   <avg>81</avg>
   <dob>22-10-1991</dob>        
    <mobileno>9849984901</mobileno>         
   <distinction>YES</distinction>
 </student>
 <student>         
   <regno>170027</regno>
   <name>Surya</name>    
   <avg>98</avg>
   <dob>01-01-1994</dob>  
         
    <mobileno>9849984901</mobileno>          
   <distinction>YES</distinction>
 </student>
 <student>         
   <regno>170028</regno>
   <name>Ganesh</name>    
   <avg>90</avg>
   <dob>30-12-1992</dob>         
   <mobileno>9849984901</mobileno>         
   <distinction>YES</distinction>
 </student>
 
</students_info>
